### PR TITLE
Update README.md to provide more installation guide and examples

### LINKED ISSUE #21: Update README.md

### PR DESCRIPTION
**Pull request by ritazh**
Closes #21

### CODE REVIEW

**Comment by sedouard** [comment]
For the file association gif, you should just show the file explorer with the nodejs icon on a *.zzz file.

**Comment by ritazh** [comment]
Uploaded a new screen shot for file association.

**Comment by sedouard** [comment]
Thanks!

**Comment by ritazh** [comment]
In order for the images to show up, it's expecting a branch called `fix_readme`.

**Comment by sedouard** [comment]
Can you send another PR fixing it?

**Comment by ritazh** [comment]
I don't think I can create the branch here.

**Comment by sedouard** [comment]
Congrats you've graduated to `Collaborator` ;-)

**Comment by ritazh** [comment]
:+1:

**Pull request merged**
