### PR TITLE
swap a console.log for debug

### PR DESCRIPTION
**Pull request by shiftkey**
Not sure if this is intended to be around at all, I'm not too familiar with the codebase.

### CODE REVIEW

**Comment by RupW** [comment]
This fixes #47

**Comment by ritazh** [comment]
Thanks for your contribution @shiftkey !

**Comment by norlin** [comment]
@ritazh please release the updated version to NPM. The on in the npm and also the one in the Releases here on the github are still contains the `console.log` instead of `debug`

**Comment by ritazh** [comment]
@norlin done https://www.npmjs.com/package/windows-registry?activeTab=versions

**Pull request merged**
